apiVersion: apps/v1
kind: Deployment

metadata:
  name: loki-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: loki

  template:
    metadata:
      labels:
        app: loki

    spec:
      containers:
        - name: loki

          image: grafana/loki:latest

          ports:
            - containerPort: 3100

          args:
            - "-config.file=/etc/loki/loki.yaml"

          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki

      volumes:
        - name: loki-config-volume

          configMap:
            name: loki-config